//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRaoVat.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBRaoVatEntities : DbContext
    {
        public DBRaoVatEntities()
            : base("name=DBRaoVatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaiDang> BaiDangs { get; set; }
        public virtual DbSet<BaiLuu> BaiLuus { get; set; }
        public virtual DbSet<ChuyenMuc> ChuyenMucs { get; set; }
        public virtual DbSet<DanhGia> DanhGias { get; set; }
        public virtual DbSet<DanhMuc> DanhMucs { get; set; }
        public virtual DbSet<GiaoDich> GiaoDiches { get; set; }
        public virtual DbSet<Hinh> Hinhs { get; set; }
        public virtual DbSet<LoaiBaiDang> LoaiBaiDangs { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<Quyen> Quyens { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ThoiGianBaiDangTrangChu> ThoiGianBaiDangTrangChus { get; set; }
        public virtual DbSet<TinhTrangBaiDang> TinhTrangBaiDangs { get; set; }
        public virtual DbSet<TinhTrangSanPham> TinhTrangSanPhams { get; set; }
        public virtual DbSet<Vung> Vungs { get; set; }
    }
}
