//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRaoVat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguoiDung()
        {
            this.BaiDangs = new HashSet<BaiDang>();
            this.BaiLuus = new HashSet<BaiLuu>();
            this.DanhGias = new HashSet<DanhGia>();
            this.DanhGias1 = new HashSet<DanhGia>();
        }
    
        public int maNguoiDung { get; set; }
        public int maQuyen { get; set; }
        public string ten { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string SDT { get; set; }
        public int xu { get; set; }
        public Nullable<double> slRate { get; set; }
        public Nullable<double> tongRate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaiDang> BaiDangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaiLuu> BaiLuus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGias1 { get; set; }
        public virtual Quyen Quyen { get; set; }
    }
}
